### ISSUE TITLE
Saving model non-working

### ISSUE THREAD

**Issue by jbcoffin** [matchms/ms2deepscore#123]
Following MS2DeepScore_tutorial.ipynb,
` model.save(model_file_name)` return ' AttributeError: 'Adam' object has no attribute 'weights' '.
A file is generated but it is unusable, spectrum_binner and additional_input are missing.

- python 3.8.16 (default, Jan 17 2023, 23:13:24)  [GCC 11.2.0]
- matchms 0.18.0 (same issue with 0.16.0)
- ms2deepscore 0.3.1
- tensorflow 2.11.0

**Comment by justinjjvanderhooft** [comment]
@florian-huber could this have to do with the recent matchms update, or with the recent ms2deepscore additions?

**Comment by niekdejonge** [comment]
I think this issue is not version dependent, but has to do with a small mistake in the tutorial. For the implementation in MS2Query this was solved and can be found here: https://github.com/iomega/ms2query/blob/main/ms2query/create_new_library/train_ms2deepscore.py
Hope this helps.

**Comment by niekdejonge** [comment]
@florian-huber When trying to build a model I did run into the same error. It might be due to a new TensorFlow version since tensorflow version 2.11 the optimizers have been changed. I will look into this.

**Comment by niekdejonge** [comment]
Fixed with #129

**Comment by florian-huber** [comment]
@niekdejonge We should anyway reconsider the tensorflow versions we support.
As far as I understood, >=2.11 will no longer support Windows (only WSL2) and contains some larger changes. 
I would probably keep it for now (as introduced in #129), but drop some older versions.

**Comment by florian-huber** [comment]
I fixed the failing tensorflow test (reason was that a higher numpy version was needed).
At the moment we test tensorflow 2.4, 2.6, 2.8 and the most recent version (2.10 to 2.12).

Should be fine for now. I would also keep the backwards checks unless it gets too much work. Mostly to make sure that models can be used and exchanged across multiple versions.
